Traceback (most recent call last):
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/mberrens/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# We will extract important information from a complicated text file.
# It is a quantum calculation output file from a software package.

def parse_output(input_name, output_name):
    energies = []
    with open(input_name) as f_obj:
        for line in f_obj:
            if 'FINAL ENERGY' in line:
                energies.append(float(line.split()[2]))
    with open(output_name, 'w') as f_obj:
        f_obj.write("Iterations    Energy \n")
        for i, energy in enumerate(energies):
            line = '%12s %12.5f \n' %('Iteration %i' %i, energy)#'Iteration %i' %i + '    ' + str(energy) + '\n'
            f_obj.write(line)
    return energies

energies = parse_output('../data/file_example3.out','../data/energies.txt')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-6-663c93cfc169>[0m in [0;36m<module>[0;34m[0m
[1;32m     15[0m     [0;32mreturn[0m [0menergies[0m[0;34m[0m[0;34m[0m[0m
[1;32m     16[0m [0;34m[0m[0m
[0;32m---> 17[0;31m [0menergies[0m [0;34m=[0m [0mparse_output[0m[0;34m([0m[0;34m'../data/file_example3.out'[0m[0;34m,[0m[0;34m'../data/energies.txt'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-6-663c93cfc169>[0m in [0;36mparse_output[0;34m(input_name, output_name)[0m
[1;32m      4[0m [0;32mdef[0m [0mparse_output[0m[0;34m([0m[0minput_name[0m[0;34m,[0m [0moutput_name[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0menergies[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m     [0;32mwith[0m [0mopen[0m[0;34m([0m[0minput_name[0m[0;34m)[0m [0;32mas[0m [0mf_obj[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m         [0;32mfor[0m [0mline[0m [0;32min[0m [0mf_obj[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m             [0;32mif[0m [0;34m'FINAL ENERGY'[0m [0;32min[0m [0mline[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../data/file_example3.out'
FileNotFoundError: [Errno 2] No such file or directory: '../data/file_example3.out'

